Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2018-10, with the labels that each got.

#155 Fix typos and formatting
  README.md
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/server.go
  cmd/aws-iam-authenticator/token.go
  cmd/aws-iam-authenticator/verify.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#161 Log the STS response on success
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 Remove broken latest flag
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Gitignore additions
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/M

#164 Bump go and goreleaser versions.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Add expiration to token creation
  cmd/aws-iam-authenticator/token.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#165 Change deprecated syntax
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 Change container repository
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#167 Change github repository
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
