Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2018-08, with the labels that each got.

#129 Add SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 Adding configs to allow you to run from local
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/root.go
  cmd/aws-iam-authenticator/server.go
  pkg/config/certs.go
  pkg/config/config.go
  pkg/config/types.go
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#126 feat(verify): creating output format option for verify command
  cmd/aws-iam-authenticator/verify.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#128 #125 Adding `version` subcommand
  .goreleaser.yaml
  .travis.yml
  Gopkg.lock
  cmd/aws-iam-authenticator/version.go
  vendor/github.com/christopherhein/go-version/CONTRIBUTING.adoc
  vendor/github.com/christopherhein/go-version/LICENSE.txt
  vendor/github.com/christopherhein/go-version/readme.adoc
  vendor/github.com/christopherhein/go-version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#134 Role assumption names
  README.md
  cmd/aws-iam-authenticator/token.go
  pkg/config/config.go
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/M
