Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2018-07, with the labels that each got.

#108 Renamed heptio-authenticator-aws -> aws-iam-authenticator
  .goreleaser.yaml
  .travis.yml
  Dockerfile.alpine-3.6
  Dockerfile.alpine-3.7
  Dockerfile.debian-jessie
  Dockerfile.debian-stretch
  Dockerfile.scratch
  Makefile
  README.md
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/root.go
  cmd/aws-iam-authenticator/server.go
  cmd/aws-iam-authenticator/token.go
  cmd/aws-iam-authenticator/verify.go
  example.yaml
  pkg/config/certs.go
  pkg/config/kubeconfig.go
  pkg/config/types.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/types.go
  pkg/token/token.go
Labels: cncf-cla: yes, lgtm, size/L

#110 Link CNCF Code of conduct and CLA directly.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, lgtm, size/M

#73 Add --log-format server flag to configure output format
  cmd/aws-iam-authenticator/root.go
Labels: cncf-cla: yes, lgtm, size/S

#113 Build release for Windows
  .goreleaser.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#122 Adding a flag to only output the token
  cmd/aws-iam-authenticator/token.go
Labels: cncf-cla: yes, size/XS
