Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2019-06, with the labels that each got.

#231 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#228 add support for passing externalID to assume role
  cmd/aws-iam-authenticator/token.go
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#237 Adding micahhausler as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#239 Lowercase ARN inside doMapping and log about it
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S
