Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2019-04, with the labels that each got.

#210 Adding chris hein as a reviewer and maintainer!
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 Adding micahhausler as reviewer and security contact
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#212 Adding justinsb as a reviewer!
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#193 Cache aws credentials
  Gopkg.lock
  Gopkg.toml
  cmd/aws-iam-authenticator/token.go
  pkg/token/filecache.go
  pkg/token/filecache_test.go
  pkg/token/token.go
  vendor/github.com/gofrs/flock/.gitignore
  vendor/github.com/gofrs/flock/.travis.yml
  vendor/github.com/gofrs/flock/LICENSE
  vendor/github.com/gofrs/flock/README.md
  vendor/github.com/gofrs/flock/appveyor.yml
  vendor/github.com/gofrs/flock/flock.go
  vendor/github.com/gofrs/flock/flock_example_test.go
  vendor/github.com/gofrs/flock/flock_test.go
  vendor/github.com/gofrs/flock/flock_unix.go
  vendor/github.com/gofrs/flock/flock_winapi.go
  vendor/github.com/gofrs/flock/flock_windows.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/example_embedded_test.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#213 fmt
  cmd/aws-iam-authenticator/root.go
  pkg/config/certs.go
  pkg/server/server.go
  pkg/token/filecache.go
  pkg/token/filecache_test.go
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#214 Move to a new ECR home
  .goreleaser.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#215 Check in changelog
  CHANGELOG-0.4.0.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#205 Fix function comments based on best practices from Effective Go
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#206 Typo!
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 Update example.yaml for Kops Usage (#1)
  example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 Update changelog
  CHANGELOG-0.4.0.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 Release v0.4.0
  .goreleaser.yaml
  example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#217 Document that base64 encoding padding must be removed from bearer token
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#178 Include aws request ID when logging errors
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS
