Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2020-02, with the labels that each got.

#291 added selector to spec and changed from extenstions to apps/v1
  deploy/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#287 Restrict ClusterRole to readonly IAMIdentityMapping access
  deploy/example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#292 Adding Rate limiting ec2:DescribeInstances API along with Batching for high TPS
  .gitignore
  Makefile
  cmd/aws-iam-authenticator/root.go
  cmd/aws-iam-authenticator/server.go
  go.mod
  go.sum
  pkg/config/types.go
  pkg/ec2provider/ec2provider.go
  pkg/ec2provider/ec2provider_test.go
  pkg/httputil/client.go
  pkg/httputil/client_test.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
