Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2020-01, with the labels that each got.

#279 Require to pass in interface instead of the concrete type
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Add AWS Access Key ID to log
  pkg/server/server.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#283 switch to use regional sts endpoint & imdsV2
  cmd/aws-iam-authenticator/token.go
  go.mod
  go.sum
  pkg/token/token.go
  vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go
  vendor/github.com/aws/aws-sdk-go/aws/awsutil/path_value.go
  vendor/github.com/aws/aws-sdk-go/aws/client/client.go
  vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/client/metadata/client_info.go
  vendor/github.com/aws/aws-sdk-go/aws/client/no_op_retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/convert_types.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/processcreds/provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/metric_chan.go
  vendor/github.com/aws/aws-sdk-go/aws/csm/reporter.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/decode.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/endpoints.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/legacy_regions.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request.go
  vendor/github.com/aws/aws-sdk-go/aws/request/request_pagination.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/session/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/skipper.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkio/byte.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkmath/floor.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkmath/floor_go1.9.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkrand/read.go
  vendor/github.com/aws/aws-sdk-go/internal/sdkrand/read_1_5.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/timestamp.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/sort.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil/xml_to_struct.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/service.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sts/service.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#260 Remove DNS-1123 validation of usernames and groups
  deploy/example.yaml
  pkg/server/server.go
  pkg/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 Allow server port customization
  cmd/aws-iam-authenticator/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#286 Add AWS AccessKeyID as an extra field in UserInfo
  pkg/server/server.go
  pkg/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
