Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2020-12, with the labels that each got.

#359 Added user agent to AWS SDK
  .goreleaser.yaml
  cmd/aws-iam-authenticator/version.go
  pkg/ec2provider/ec2provider.go
  pkg/token/token.go
  pkg/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#352 Support IPv6 listen address
  pkg/config/certs.go
  pkg/config/certs_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/types.go
  pkg/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#332 Document AccessKeyId from UserInfo
  README.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#348 (arn): validate partition against all partitions returned by the aws sdk
  pkg/arn/arn.go
  pkg/arn/arn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
