Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2020-03, with the labels that each got.

#298 Indentation and unit test improvements
  pkg/ec2provider/ec2provider_test.go
  pkg/httputil/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#302 chown aws-iam-authenticator to avoid permission denied
  Dockerfile.alpine-3.6
  Dockerfile.alpine-3.7
  Dockerfile.amazonlinux-2
  Dockerfile.debian-jessie
  Dockerfile.debian-stretch
  Dockerfile.scratch
Labels: approved, cncf-cla: yes, lgtm, size/XS

#306 Update aws-sdk-go to version v1.30.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S
