Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2021-11, with the labels that each got.

#411 Fix missing status definition in v1 CRD
  deploy/iamidentitymapping.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#410 Fix panic when cache file can't be Stat-ed
  pkg/token/filecache.go
  pkg/token/filecache_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#396 Fix deps
  cmd/aws-iam-authenticator/version.go
  go.mod
  go.sum
  vendor/go.hein.dev/go-version/.gitignore
  vendor/go.hein.dev/go-version/.travis.yml
  vendor/go.hein.dev/go-version/CHANGELOG.md
  vendor/go.hein.dev/go-version/CONTRIBUTING.adoc
  vendor/go.hein.dev/go-version/LICENSE.txt
  vendor/go.hein.dev/go-version/Makefile
  vendor/go.hein.dev/go-version/VERSION
  vendor/go.hein.dev/go-version/go.mod
  vendor/go.hein.dev/go-version/go.sum
  vendor/go.hein.dev/go-version/readme.adoc
  vendor/go.hein.dev/go-version/version.go
  vendor/modules.txt
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#407 Add jaypipes to approvers/reviewers
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm
