Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2021-09, with the labels that each got.

#394 Add cloudbuild & improvements
  .gitignore
  Dockerfile
  Makefile
  cloudbuild.yaml
  cmd/aws-iam-authenticator/version.go
  pkg/version.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#399 Move inactives to emeritus_approvers and add active users
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#397 Upgrade CRD manifest to v1
  deploy/iamidentitymapping.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm
