Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2021-07, with the labels that each got.

#386 [pkg/token]: Update credential API version
  README.md
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#376 doc: fix typo in RELEASE.md
  docs/RELEASE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#371 goreleaser: bump release to 0.164.0 and fix config deprecations
  .goreleaser.yaml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#381 *: add user/role subcommands
  cmd/aws-iam-authenticator/add.go
  go.mod
  go.sum
  pkg/config/types.go
  pkg/mapper/configmap/client/client.go
  pkg/mapper/configmap/client/client_test.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/configmap/configmap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#390 Fix typo
  pkg/token/token.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
