Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2022-11, with the labels that each got.

#505 remove dependency from PR #416
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#507 Add end to end test for mountfile mode
  Makefile
  hack/dev/extract_ca_data.py
  hack/e2e-dynamicfile.sh
  hack/start-dev-env-dynamicfile.sh
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test, lgtm

#510 prepare v0.5.11 release
  .gitignore
  Dockerfile
  Makefile
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/root.go
  cmd/aws-iam-authenticator/server.go
  empty
  go.mod
  go.sum
  hack/dev/access-entries.json
  hack/dev/access-entries.template
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/dev/extract_ca_data.py
  hack/dev/policies.template
  hack/e2e-dynamicfile.sh
  hack/e2e/README.md
  hack/e2e/apiserver-restart.yaml
  hack/e2e/aws.sh
  hack/e2e/deploy.yaml
  hack/e2e/kops-patch.yaml
  hack/e2e/kops.sh
  hack/e2e/kubeconfig-update.yaml
  hack/e2e/roles.yaml
  hack/e2e/run.sh
  hack/e2e/util.sh
  hack/lib/dev-env.sh
  hack/start-dev-env-dynamicfile.sh
  hack/update-gomod.sh
  pkg/config/features.go
  pkg/config/types.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  tests/e2e/apiserver_test.go
  tests/e2e/suite_test.go
  tests/e2e/tests.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#509 Revert "Add SSO Role suffix support (#416)"
  .gitignore
  cmd/aws-iam-authenticator/add.go
  cmd/aws-iam-authenticator/root.go
  docs/sso_role_matcher.md
  pkg/arn/arnlike.go
  pkg/arn/arnlike_test.go
  pkg/config/features.go
  pkg/config/mapper.go
  pkg/config/mapper_test.go
  pkg/config/types.go
  pkg/mapper/configmap/client/client.go
  pkg/mapper/configmap/client/client_test.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/configmap/configmap_test.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/file/mapper.go
  pkg/mapper/file/mapper_test.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#511 move e2e test from start dev script + minor fix for run.sh
  Makefile
  hack/e2e-dynamicfile.sh
  hack/e2e/run.sh
  hack/start-dev-env-dynamicfile.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#515 Update to version v0.5.11
  Makefile
Labels: cncf-cla: yes, approved, size/XS

#517 Added Issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report-client.yaml
  .github/ISSUE_TEMPLATE/bug-report-server.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#513 add install kind into e2e script
  Makefile
  hack/dev/allow_assume_role_policy.template
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  hack/start-dev-env-dynamicfile.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#519 update Dockerfile to pull from https://gallery.ecr.aws/eks-distro-bui…
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#516 Cherry pick: solve the problem that client-go cannot find v1alpha1 after upgrading to 0.24
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#525 Bump aws sdk go to v1.44.145
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#520 fix Makefile on branch release-0.5
  Makefile
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm
