Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2022-10, with the labels that each got.

#493 Automated cherry pick of #491: Bump aws sdk go to v1.44.107
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/M, ok-to-test

#490 fix on the script to solve permission denied issue when run make start-dev
  hack/lib/dev-env.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#488 Add new backend mode DYNAMICFILE
  cmd/aws-iam-authenticator/root.go
  go.mod
  pkg/config/types.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#499 Print version on startup
  cmd/aws-iam-authenticator/root.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#500 Update to v0.6.0
  Makefile
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/root.go
  cmd/aws-iam-authenticator/server.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#501 add end to end test for dynamicfile backend mode
  Makefile
  hack/dev/access-entries.json
  hack/dev/access-entries.template
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/dev/policies.template
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  hack/start-dev-env-dynamicfile.sh
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#503 Bump Version in Makefile
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
