Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2022-08, with the labels that each got.

#475 Have init generate files directly in destination folder
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/root.go
  pkg/config/features.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#474 solve the problem that client-go cannot find v1alpha1 after upgrading to 0.24
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#476 End-to-end testing framework for IAM authenticator
  .gitignore
  go.mod
  go.sum
  hack/e2e/README.md
  hack/e2e/apiserver-restart.yaml
  hack/e2e/aws.sh
  hack/e2e/deploy.yaml
  hack/e2e/kops-patch.yaml
  hack/e2e/kops.sh
  hack/e2e/kubeconfig-update.yaml
  hack/e2e/roles.yaml
  hack/e2e/run.sh
  hack/e2e/util.sh
  hack/update-gomod.sh
  tests/e2e/apiserver_test.go
  tests/e2e/suite_test.go
  tests/e2e/tests.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#478 Add e2e test recipe to Makefile
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#479 Non-blocking E2E tests
  empty
  hack/e2e/README.md
  hack/e2e/aws.sh
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#480 Working E2E tests in prow
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#477 Initialize metrics in NewVerifier() if needed
  pkg/metrics/metrics.go
  pkg/token/token.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test
