Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2022-02, with the labels that each got.

#417 Build multi-arch images
  .goreleaser.yaml
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#414 Bump Go to 1.17 in Travis
  .travis.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#426 Embed go-runner into the image
  Dockerfile
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#425 [1/2] Release 0.5.4
  CHANGELOG.md
  docs/RELEASE.md
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#423 Don't pass metrics around
  cmd/aws-iam-authenticator/server.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/configmap/configmap_test.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/configmap/yaml_test.go
  pkg/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/types.go
  tests/integration/go.mod
  tests/integration/testutils/testserver.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#431 Simplify goreleaser Dockerfiles
  .goreleaser.yaml
  Dockerfile.alpine-3.6
  Dockerfile.alpine-3.7
  Dockerfile.amazonlinux-2
  Dockerfile.debian-stretch
  Dockerfile.goreleaser
  Dockerfile.scratch
  Makefile
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#432 Rename configmap_watch_failures to configmap_watch_failures_total
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#428 emit metric for EC2 describeInstance calls
  pkg/ec2provider/ec2provider.go
  pkg/ec2provider/ec2provider_test.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#430 add sts error metric
  pkg/metrics/metrics.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#433 Use full package name for goreleaser version
  .goreleaser.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#434 Update changelog for release v0.5.5 [1/2]
  CHANGELOG.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#429 Add jyotimahapatra to approvers/reviewers
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm
