Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2022-07, with the labels that each got.

#470 Bump version in Makefile
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#471 Bump 0.6
  Makefile
Labels: cncf-cla: yes, approved, size/XS

#467 Fix several deprecations/removals in example deploy manifests
  deploy/example.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#464 Lowercase the ARN keys
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test
