Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-05, with the labels that each got.

#595 Enable cross-compilation in Dockerfile
  Dockerfile
  Makefile
Labels: cncf-cla: yes, size/S, approved, lgtm

#596 Bump golang.org/x/net to v.0.7.0 to fix CVE-2022-41723
  go.mod
  go.sum
  tests/integration/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#599 Release 0.6.10
  Dockerfile
  Makefile
  go.mod
  go.sum
  tests/integration/go.sum
  version.txt
Labels: cncf-cla: yes, size/M, approved, lgtm
