Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-03, with the labels that each got.

#569 Update base image in Docker file
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#570 Update base image in Docker file
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#571 update the aws sdk go version to latest
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#572 update the aws sdk go version to latest
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#573 update the aws sdk go version to latest
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#574 Release v0.5.14
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#575 Release v0.6.5
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#568 Add Username Prefix Enforce for DynamicFile mode
  README.md
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries-username-prefix.template
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#576 Add Username Prefix Enforce for DynamicFile mode
  README.md
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries-username-prefix.template
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#577 Add Username Prefix Enforce for DynamicFile mode
  README.md
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries-username-prefix.template
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#578 release v0.5.15
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#579 Release v0.6.6
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#580 release v0.6.7
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#585 release v0.6.8
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm
