Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-02, with the labels that each got.

#506 Support un-canonicalized ARNs in filemapper
  pkg/mapper/file/mapper.go
  pkg/mapper/file/mapper_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#552 Expose Principal Id to audit log
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#556 Add default instance region in sts hostname
  cmd/aws-iam-authenticator/verify.go
  pkg/ec2provider/ec2provider.go
  pkg/server/server.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#557 Add default instance region in sts hostname
  cmd/aws-iam-authenticator/verify.go
  pkg/ec2provider/ec2provider.go
  pkg/server/server.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#558 Add default instance region in sts hostname
  cmd/aws-iam-authenticator/verify.go
  pkg/ec2provider/ec2provider.go
  pkg/server/server.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#561 Install kind if it doesn't exist to _output
  hack/lib/dev-env.sh
  hack/start-dev-env.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#554 Enable Mapping on UserID
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries.template
  hack/e2e-dynamicfile.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/file/mapper_test.go
  pkg/mapper/mapper.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#563 Prepare release v0.5.14
  .goreleaser.yaml
  cloudbuild.yaml
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries.template
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  hack/start-dev-env.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#564 prepare new release v0.6.4
  .goreleaser.yaml
  cloudbuild.yaml
  cmd/aws-iam-authenticator/root.go
  hack/dev/access-entries.template
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  hack/start-dev-env.sh
  pkg/config/types.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#565 Tag release on update to version.txt
  .github/workflows/tag-release.yml
  Makefile
  hack/get-version.sh
  hack/tag-release.sh
  version.txt
Labels: cncf-cla: yes, size/M, approved, lgtm

#559 Release v0.6.4
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#566 Release v0.5.13
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#567 Update base image in Docker file
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm
