Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-09, with the labels that each got.

#629 Switch to new community owned account
  hack/e2e/run.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm

#598 Build improvements
  Makefile
  cmd/aws-iam-authenticator/add.go
  cmd/aws-iam-authenticator/init.go
  cmd/aws-iam-authenticator/server.go
  cmd/aws-iam-authenticator/token.go
  cmd/aws-iam-authenticator/verify.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#630 return 429 for STS throttling
  pkg/metrics/metrics.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm
