Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-12, with the labels that each got.

#658 Cherry-pick: Update go to 1.21.4 (#648)
  .github/workflows/deps.yml
  Dockerfile
Labels: cncf-cla: yes, size/M, approved, lgtm, do-not-merge/hold

#659 Cherry-pick: Update go to 1.21.4 (#648)
  .github/workflows/deps.yml
  Dockerfile
Labels: cncf-cla: yes, size/S, approved, lgtm

#661 Update go to 1.21.5
  .github/workflows/deps.yml
  Dockerfile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm

#660 Check ARN for user ID strict check
  pkg/config/mapper.go
  pkg/errutil/errors.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#662 Cherry-pick: Update go to 1.21.5
  .github/workflows/deps.yml
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#665 Cherry-pick: Check ARN for user ID strict check (#660)
  pkg/config/mapper.go
  pkg/errutil/errors.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#664 Cherry-pick: Check ARN for user ID strict check (#660)
  pkg/config/mapper.go
  pkg/errutil/errors.go
  pkg/mapper/configmap/mapper.go
  pkg/mapper/crd/mapper.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/mapper/file/mapper.go
  pkg/mapper/mapper.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#666 Release v0.6.14
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#667 Release v0.5.21
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#669 Fix role ARN comparison for user ID strict check
  pkg/arn/arn.go
  pkg/arn/arn_test.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#671 Fix role ARN comparison for user ID strict check (#669)
  pkg/arn/arn.go
  pkg/arn/arn_test.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#670 Fix role ARN comparison for user ID strict check (#669)
  pkg/arn/arn.go
  pkg/arn/arn_test.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#672 Release 0.6.15
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#673 Release 0.5.22
  version.txt
Labels: cncf-cla: yes, size/XS, ok-to-test

#674 fix arn comparison for IAM ARN
  pkg/mapper/dynamicfile/mapper.go
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#675 release v0.6.16
  pkg/mapper/dynamicfile/mapper.go
  version.txt
Labels: cncf-cla: yes, size/S, approved, lgtm

#676 release v0.5.23
  pkg/mapper/dynamicfile/mapper.go
  version.txt
Labels: cncf-cla: yes, size/S, approved, lgtm

#679 fix base image to use latest
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm
