Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-01, with the labels that each got.

#540 Build s390x/ppc64le binaries
  .goreleaser.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#544 Release v0.6.3
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#547 Bump dependencies and go version (in go.mod)
  go.mod
  go.sum
  pkg/server/server.go
  tests/e2e/apiserver_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/e2e/suite_test.go
  tests/e2e/tests.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/server/main_test.go
  tests/integration/server/server_test.go
  tests/integration/testutils/testserver.go
Labels: cncf-cla: yes, approved, size/XXL, lgtm

#542 Migrate away from google.com gcp project k8s-testimages
  cloudbuild.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm
