Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-10, with the labels that each got.

#628 Fix issue 606: use latest version of aws-sdk-go
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#633 Stricter dependency/security review / Do not use AWS internal image(s)
  .github/workflows/deps.yml
  Dockerfile
  go.mod
  go.sum
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#634 Remove replace line
  go.mod
Labels: cncf-cla: yes, approved, size/XS, lgtm
