Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-11, with the labels that each got.

#641 Add `dims` to SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#648 Update go to 1.21.4
  .github/workflows/deps.yml
  Dockerfile
  go.mod
Labels: cncf-cla: yes, size/S, approved

#649 Remove govulncheck on test deps temporarily
  .github/workflows/deps.yml
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/XL

#644 Fix federated user ID parsing
  pkg/arn/arn.go
  pkg/arn/arn_test.go
  pkg/mapper/crd/controller/controller.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/file/mapper.go
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#652 Change s3 bucket for e2e tests, current default exists somewhere
  hack/e2e/run.sh
Labels: cncf-cla: yes, approved, size/XS

#653 Cherry-pick: Change s3 bucket for e2e tests, current default exists somewhere
  hack/e2e/run.sh
Labels: cncf-cla: yes, approved, size/XS

#651 Cherry-pick: Fix issue 606: use latest version of aws-sdk-go
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved

#650 Cherry-pick: Fix issue 606: use latest version of aws-sdk-go
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/S, approved

#654 Cherry-pick: Fix federated user ID parsing #644
  go.mod
  go.sum
  pkg/arn/arn.go
  pkg/arn/arn_test.go
  pkg/mapper/crd/controller/controller.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/file/mapper.go
  pkg/token/token.go
  pkg/token/token_test.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/XL

#655 Release v0.6.13
  version.txt
Labels: cncf-cla: yes, approved, size/XS

#656 Release v0.5.20
  version.txt
Labels: cncf-cla: yes, approved, size/XS
