Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2023-07, with the labels that each got.

#612 add Dynamic Backend Mode support
  Makefile
  cmd/aws-iam-authenticator/root.go
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  pkg/config/types.go
  pkg/fileutil/util.go
  pkg/fileutil/util_test.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/types.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#614 Prepare new release
  Makefile
  cmd/aws-iam-authenticator/root.go
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  pkg/config/types.go
  pkg/fileutil/util.go
  pkg/fileutil/util_test.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/types.go
Labels: cncf-cla: yes, approved, lgtm, size/XL

#592 Fix readme 404 link
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#615 tag 0.6.11
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#616 cherry pick and release 0.5.18
  .github/workflows/create-release.yml
  Dockerfile
  Makefile
  cmd/aws-iam-authenticator/root.go
  go.mod
  go.sum
  hack/dev/authenticator_with_dynamicfile_mode.yaml
  hack/e2e-dynamicfile.sh
  hack/lib/dev-env.sh
  pkg/config/types.go
  pkg/fileutil/util.go
  pkg/fileutil/util_test.go
  pkg/mapper/configmap/configmap.go
  pkg/mapper/dynamicfile/dynamicfile.go
  pkg/mapper/dynamicfile/dynamicfile_test.go
  pkg/mapper/dynamicfile/mapper.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/types.go
  tests/integration/go.sum
  version.txt
Labels: cncf-cla: yes, approved, lgtm, size/XL

#610 build-all-bins should build darwin/arm64 as well
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm
