Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2024-09, with the labels that each got.

#755 Refactored token filecache
  go.mod
  pkg/filecache/filecache.go
  pkg/filecache/filecache_test.go
  pkg/token/token.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL

#756 Filecache sdk upgrade
  go.mod
  go.sum
  pkg/filecache/converter.go
  pkg/filecache/filecache.go
  pkg/filecache/filecache_test.go
  pkg/token/token.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#760 use protobuf content type instead of json for k8s client
  cmd/aws-iam-authenticator/add.go
  pkg/mapper/configmap/configmap.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#761 use protobuf content type instead of json for k8s client
  cmd/aws-iam-authenticator/add.go
  pkg/mapper/configmap/configmap.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#763 Create new release 0.6.27
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#758 Update RELEASE.md
  CHANGELOG.md
  deploy/example.yaml
  docs/RELEASE.md
  hack/changelog.py
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test
