Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2024-06, with the labels that each got.

#726 fix: Update goreleaser workflow to fix warnings and artifact generation
  .github/workflows/create-release.yml
  .github/workflows/tag-release.yml
  .goreleaser.yaml
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#731 update aws go sdk to v1.54.6
  .github/workflows/create-release.yml
  .github/workflows/tag-release.yml
  .go-version
  .goreleaser.yaml
  Dockerfile
  OWNERS
  SECURITY_CONTACTS
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#732 cut new release v0.6.21
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
