Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2024-12, with the labels that each got.

#779 chore: Add dependabot configuration to automatically check for package updates weekly
  .github/dependabot.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#778 handle scenario when the file is created but doesn't have content
  pkg/fileutil/util.go
  pkg/fileutil/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#787 handle scenario when the file is created but doesn't have content
  pkg/fileutil/util.go
  pkg/fileutil/util_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#785 deps: Update `golang.org/x/crypto` library to remediate high CVE
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#786 chore: Update to go `1.23.4`
  .go-version
  Dockerfile
  go.mod
  tests/e2e/go.mod
  tests/integration/go.mod
Labels: cncf-cla: yes, size/S, approved, lgtm

#789 Update upstream dependencies to v1.32.0
  go.mod
  go.sum
  pkg/mapper/configmap/configmap_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#795 Cherry pick commits from master branch
  .go-version
  Dockerfile
  go.mod
  go.sum
  pkg/mapper/configmap/configmap_test.go
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#796 create new release 0.6.29
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#793 fix: Correct codgen script due to deprecated script removal
  hack/update-codegen.sh
  pkg/mapper/crd/apis/iamauthenticator/v1alpha1/zz_generated.deepcopy.go
  pkg/mapper/crd/generated/clientset/versioned/clientset.go
  pkg/mapper/crd/generated/clientset/versioned/doc.go
  pkg/mapper/crd/generated/clientset/versioned/fake/clientset_generated.go
  pkg/mapper/crd/generated/clientset/versioned/typed/iamauthenticator/v1alpha1/fake/fake_iamauthenticator_client.go
  pkg/mapper/crd/generated/clientset/versioned/typed/iamauthenticator/v1alpha1/fake/fake_iamidentitymapping.go
  pkg/mapper/crd/generated/clientset/versioned/typed/iamauthenticator/v1alpha1/iamauthenticator_client.go
  pkg/mapper/crd/generated/clientset/versioned/typed/iamauthenticator/v1alpha1/iamidentitymapping.go
  pkg/mapper/crd/generated/informers/externalversions/factory.go
  pkg/mapper/crd/generated/informers/externalversions/generic.go
  pkg/mapper/crd/generated/informers/externalversions/iamauthenticator/v1alpha1/iamidentitymapping.go
  pkg/mapper/crd/generated/listers/iamauthenticator/v1alpha1/iamidentitymapping.go
Labels: cncf-cla: yes, approved, lgtm, size/XL
