Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2024-01, with the labels that each got.

#683 adding nnmin-aws into reviewers
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#682 CVE fix and release v0.6.17
  Dockerfile
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#681 Replace deprecated `ioutil` package
  pkg/mapper/configmap/yaml_test.go
  pkg/server/server_test.go
  pkg/token/filecache.go
  pkg/token/token.go
  pkg/token/token_test.go
  tests/e2e/apiserver_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#685 CVE fix and release v0.5.24
  Dockerfile
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#593 fix semantic error
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#639 Repo controlled build go version
  .github/workflows/deps.yml
  .gitignore
  .go-version
  Dockerfile
  Makefile
  hack/setup-go.sh
  hack/test-integration.sh
  hack/test-unit.sh
Labels: cncf-cla: yes, size/M, approved, lgtm
