Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2024-08, with the labels that each got.

#739 Update upstream dependencies to v1.31.0
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#740 Update upstream dependencies to v1.31.0
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
  version.txt
Labels: cncf-cla: yes, approved, size/XXL, lgtm, ok-to-test

#744 update the image to latest to fix CVE-2024-39689
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#745 update the image to latest to fix CVE-2024-39689
  Dockerfile
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#746 create new release 0.6.24
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#743 add a namespaced field
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#747 Update 0.6 branch with new namespaced user info field
  pkg/server/server.go
  pkg/server/server_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#748 create new release 0.6.25
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#741 Add configurable Now time for signature generation
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#750 Remove parameterized AWS session from token.go
  pkg/token/token.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#749 Add sourceArn to sts through headers
  cmd/aws-iam-authenticator/root.go
  pkg/config/types.go
  pkg/ec2provider/ec2provider.go
  pkg/ec2provider/ec2provider_test.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#751 Add sourceArn to sts through headers
  cmd/aws-iam-authenticator/root.go
  pkg/config/types.go
  pkg/ec2provider/ec2provider.go
  pkg/ec2provider/ec2provider_test.go
  pkg/server/server.go
Labels: cncf-cla: yes, approved, size/L, lgtm, ok-to-test

#752 Create new release 0.6.26
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#753 Fix x-amz-expires header value
  pkg/token/token.go
  pkg/token/token_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
