Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2025-04, with the labels that each got.

#836 Bump release version to 0.6.31
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm

#839 update the go version to 1.24.2
  .go-version
  Dockerfile
  go.mod
  tests/e2e/go.mod
  tests/integration/go.mod
Labels: cncf-cla: yes, size/S, approved, lgtm

#812 release authenticator from mainline with 0.7.0
  .github/workflows/create-release.yml
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#840 remove validations on release branch
  hack/tag-release.sh
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#844 v1.33.0 Release
  cmd/aws-iam-authenticator/server.go
  go.mod
  go.sum
  tests/e2e/go.mod
  tests/e2e/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#849 update version txt
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
