Repository kubernetes-sigs/aws-iam-authenticator, pull requests merged in 2025-06, with the labels that each got.

#772 Log level setting + refactor filecache logs to use logrus
  cmd/aws-iam-authenticator/root.go
  pkg/filecache/filecache.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#861 Bump K8s and kops versions for E2E tests
  deploy/example.yaml
  hack/e2e/README.md
  hack/e2e/apiserver-restart.yaml
  hack/e2e/deploy.yaml
  hack/e2e/run.sh
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#856 Partial upgrade of AWS SDK Go packages from V1 to V2
  cmd/aws-iam-authenticator/server.go
  cmd/aws-iam-authenticator/token.go
  go.mod
  go.sum
  pkg/arn/arn.go
  pkg/ec2provider/ec2provider.go
  pkg/ec2provider/ec2provider_test.go
  pkg/filecache/converter.go
  pkg/filecache/filecache.go
  pkg/filecache/filecache_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/token/token.go
  pkg/token/token_test.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/testutils/testserver.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, ok-to-test

#867 update go version to 1.24.4
  .go-version
  Dockerfile
  go.mod
  tests/integration/go.mod
Labels: cncf-cla: yes, size/S, approved, lgtm, ok-to-test

#868 update Approvers/reviewers
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#869 update version to 0.7.3
  version.txt
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
